# Business Model Canvas


## What is this document?
This is a living document giving a high-level view of the business model canvas for the Spring 2020 CMPS 420 group. As the project changes and adapts over time so will this document. All members of the team are encouraged to keep this document up to date and provide feedback over the course of the project.


## Customer Segments
Users {nbsp} +
- People who want to monitor their calorie intake {nbsp} +
- People looking to find new take on a diet website {nbsp} +
- People seeking to learn healthy eating habits {nbsp} +

Advertisers {nbsp} +
- Companies looking to sell work out equipment {nbsp} +
- Companies looking to sell meal plans {nbsp} +
- Companies looking to sell gym memberships {nbsp} +


## Value Proposition
Users {nbsp} +
- Best way to track your calorie intake {nbsp} +
{nbsp} +
Advertisers {nbsp} +
- Reach possible consumers via website ads

## Channels
Website {nbsp} +
- {nbsp} +
{nbsp} +
Mobile Website {nbsp} +
- {nbsp} +

## Customer Relationships
Customer Service {nbsp} +
- Website {nbsp} +
{nbsp} +
Social Media {nbsp} +
- Twitter {nbsp} +
- Facebook {nbsp} +

## Customer Relationships
Ads {nbsp} +
- website ads {nbsp} +
{nbsp} +
Membership Fee {nbsp} +
- Premium fee to remove website ads {nbsp} +

## Key Resources
Technology {nbsp} +
- Github {nbsp} +
- Slack {nbsp} +

## Key Partners
Development Team {nbsp} +
- CMPS 480 Senior Project Members {nbsp} +
{nbsp} +
Advisors {nbsp} +
- Mark Voortman

## Key Activities
Works in Progress
- Creating a working website
- Creating a working mobile website
- Creating a database with calorie information


## Cost
Technical {nbsp} +
- Development {nbsp} +
- Website maintenance {nbsp} +

-------------------------------------------------

## Beta User Feedback
Ryan Bracalielly {nbsp} +
3 beta users review and offer feedback on the applicaiton 4/11/2020 {nbsp} +
Hypothesis was was the user would sign in, add calories, and use reports to get feedback. {nbsp} +
User 1 - Tim {nbsp} +
- Sign up page should clear user or auto sign in upon creating new user {nbsp} +
- Calorie Limit and Calorie Gaol needs defined {nbsp} +
- Need to remove browser alerts with error messages to be seen by users {nbsp} +
- Use a dynamically expanding table for meals and drinks {nbsp} +
- Better definitions across the board {nbsp} +
- Bootstrapping for mobile devices {nbsp} +
- Premise is sound as a base idea {nbsp} +
User 2 - Chris {nbsp} +
- Need to remove browser alerts with error messages to be seen by users {nbsp} +
- Should be using SSL {nbsp} +
- Asked if passwords are plain text or encrypted in some in MySQL. Advised, if not, that should be implemented. {nbsp} +
- More reporting options for daily, weekly, and monthly {nbsp} +
- Calorie Limit and Calorie Gaol needs defined {nbsp} +
- Advised reviewing the layout for hydration level, found it confusing {nbsp} +
- Should have more data validation done for various fields {nbsp} +
User 3 - Lawerence {nbsp} +
- Need to remove browser alerts with error messages to be seen by users {nbsp} +
- More reporting options for daily, weekly, and monthly {nbsp} +
- Add reporting to advise the user to show trends for under-eating and overeating {nbsp} +
- Sign up page should clear user or auto sign in upon creating new user {nbsp} +
- Advised reviewing the layout for hydration level, found it confusing {nbsp} +
- Calorie Limit and Calorie Gaol needs defined {nbsp} +

-------------------------------------------------------------

Eric Roland {nbsp} +
User - Laura {nbsp} +
- Need guidance on what calorie limit should be, and what goal should be for me {nbsp} +
- After creating my account I should be auto signed in. {nbsp} +
- Should be able to add a previous days meals {nbsp} +
- After sign in, should be able to see where I stand for the day so far {nbsp} +
- Would be great to have input on how many calories my meal was {nbsp} +
User - Brian {nbsp} +
- I don't know what my BMI is, can't this be calculated by height and weight? {nbsp} +
- I don't know what my calorie limit is? Can this be calculated? {nbsp} +
- Should be signed in after signing up. {nbsp} +
- After I add meals, the form should be cleared {nbsp} +
- Give me warning when I'm going over my calorie intake. {nbsp} +
- Do not like the click alert when I login. {nbsp} +

-----------------------------------------------------------

Connor Feals
User - Tyler userID 23
- Landing Page Feedback
  - Looks like an image was supposed to be at the top of page, it is 404
  - Lots of info at once.  Could just show a login for existing users and then have a sign up link for new users.  Click sign up            and then all the other fields could come in
  - Why do you need a user name if the login just uses email address?
  - Password confirmation field might be good idea
  - If you ask for height and weight first can't you just calculate BMI?
  - If you re-work landing page to be sign on and then separate link, on new user info submission you can navigate back to the regular landing page so new user can login
- User Information Feedback
  - Image at top of this page is 404 also
  - Similar feedback as above, might be nice to reduce the info presented at once.  Could have a page with jump points to 'Calorie Tracking', 'Daily Hydration', and then 'Reporting'
  - Added calories for 3 meals and saved, appears to work
  - Date picker control for the reports would be nice
  - Clicked 'Submit Dates For Report' and quickly blinks what I think says 'Loading Data' but that disappears and no report


## Document History
- Ryan Bracalielly created version 1.0 3/5/2020 at 11:49 PM EST
- Ryan Bracalielly created version 1.1 4/11/2020 at 2:00 PM EST
- Eric Roland created version 1.2 4/11/2020 at 10:00 PM EST
